// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/controllers/notification_scheduler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i10;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i11;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i13;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i15;
import 'package:flutter_local_notifications/src/types.dart' as _i16;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/controllers/notification_planner.dart' as _i2;
import 'package:mona/data/model/molecule.dart' as _i6;
import 'package:mona/data/model/placement.dart' as _i7;
import 'package:mona/data/model/planned_notification.dart' as _i3;
import 'package:mona/data/model/units.dart' as _i5;
import 'package:mona/services/preferences_service.dart' as _i4;
import 'package:timezone/timezone.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationPlanner].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationPlanner extends _i1.Mock
    implements _i2.NotificationPlanner {
  @override
  List<_i3.PlannedNotification> planNotifications({required int? daysAhead}) =>
      (super.noSuchMethod(
        Invocation.method(
          #planNotifications,
          [],
          {#daysAhead: daysAhead},
        ),
        returnValue: <_i3.PlannedNotification>[],
        returnValueForMissingStub: <_i3.PlannedNotification>[],
      ) as List<_i3.PlannedNotification>);

  @override
  int daysAhead({required int? maxScheduled}) => (super.noSuchMethod(
        Invocation.method(
          #daysAhead,
          [],
          {#maxScheduled: maxScheduled},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i4.PreferencesService {
  @override
  bool get autoCheckUpdatesEnabled => (super.noSuchMethod(
        Invocation.getter(#autoCheckUpdatesEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get notificationsEnabled => (super.noSuchMethod(
        Invocation.getter(#notificationsEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Units get units => (super.noSuchMethod(
        Invocation.getter(#units),
        returnValue: _i5.Units.pg_mL_ng_dL,
        returnValueForMissingStub: _i5.Units.pg_mL_ng_dL,
      ) as _i5.Units);

  @override
  List<_i6.Molecule> get customMolecules => (super.noSuchMethod(
        Invocation.getter(#customMolecules),
        returnValue: <_i6.Molecule>[],
        returnValueForMissingStub: <_i6.Molecule>[],
      ) as List<_i6.Molecule>);

  @override
  List<_i6.Molecule> get allMolecules => (super.noSuchMethod(
        Invocation.getter(#allMolecules),
        returnValue: <_i6.Molecule>[],
        returnValueForMissingStub: <_i6.Molecule>[],
      ) as List<_i6.Molecule>);

  @override
  List<_i7.Placement> get placementsList => (super.noSuchMethod(
        Invocation.getter(#placementsList),
        returnValue: <_i7.Placement>[],
        returnValueForMissingStub: <_i7.Placement>[],
      ) as List<_i7.Placement>);

  @override
  bool get placementSuggestionPerSchedule => (super.noSuchMethod(
        Invocation.getter(#placementSuggestionPerSchedule),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i8.Future<void> setAutoCheckUpdatesEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoCheckUpdatesEnabled,
          [isEnabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setNotificationsEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [isEnabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSavedLanguageTag(String? code) => (super.noSuchMethod(
        Invocation.method(
          #setSavedLanguageTag,
          [code],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setUnits(_i5.Units? units) => (super.noSuchMethod(
        Invocation.method(
          #setUnits,
          [units],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addCustomMolecule(_i6.Molecule? molecule) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCustomMolecule,
          [molecule],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeCustomMolecule(String? name) => (super.noSuchMethod(
        Invocation.method(
          #removeCustomMolecule,
          [name],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setPlacementsList(List<_i7.Placement>? placements) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPlacementsList,
          [placements],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setPlacementSuggestionPerSchedule(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPlacementSuggestionPerSchedule,
          [isEnabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i10.FlutterLocalNotificationsPlugin {
  @override
  _i8.Future<bool?> initialize({
    required _i11.InitializationSettings? settings,
    _i12.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i12.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #settings: settings,
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i8.Future<bool?>.value(),
        returnValueForMissingStub: _i8.Future<bool?>.value(),
      ) as _i8.Future<bool?>);

  @override
  _i8.Future<_i12.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i8.Future<_i12.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i8.Future<_i12.NotificationAppLaunchDetails?>.value(),
          ) as _i8.Future<_i12.NotificationAppLaunchDetails?>);

  @override
  _i8.Future<void> show({
    required int? id,
    String? title,
    String? body,
    _i13.NotificationDetails? notificationDetails,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #notificationDetails: notificationDetails,
            #payload: payload,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancel({
    required int? id,
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
          {
            #id: id,
            #tag: tag,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelAllPendingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllPendingNotifications,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> zonedSchedule({
    required int? id,
    required _i14.TZDateTime? scheduledDate,
    required _i13.NotificationDetails? notificationDetails,
    required _i15.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
    _i16.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [],
          {
            #id: id,
            #scheduledDate: scheduledDate,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> periodicallyShow({
    required int? id,
    required _i12.RepeatInterval? repeatInterval,
    required _i13.NotificationDetails? notificationDetails,
    required _i15.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [],
          {
            #id: id,
            #repeatInterval: repeatInterval,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> periodicallyShowWithDuration({
    required int? id,
    required Duration? repeatDurationInterval,
    required _i13.NotificationDetails? notificationDetails,
    String? title,
    String? body,
    _i15.AndroidScheduleMode? androidScheduleMode =
        _i15.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [],
          {
            #id: id,
            #repeatDurationInterval: repeatDurationInterval,
            #notificationDetails: notificationDetails,
            #title: title,
            #body: body,
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i12.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue:
                _i8.Future<List<_i12.PendingNotificationRequest>>.value(
                    <_i12.PendingNotificationRequest>[]),
            returnValueForMissingStub:
                _i8.Future<List<_i12.PendingNotificationRequest>>.value(
                    <_i12.PendingNotificationRequest>[]),
          ) as _i8.Future<List<_i12.PendingNotificationRequest>>);

  @override
  _i8.Future<List<_i12.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i8.Future<List<_i12.ActiveNotification>>.value(
            <_i12.ActiveNotification>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i12.ActiveNotification>>.value(
                <_i12.ActiveNotification>[]),
      ) as _i8.Future<List<_i12.ActiveNotification>>);
}
